---

- name: (jre-debian) | check openjdk
  shell: dpkg -l | grep openjdk
  register: openjdk_installed
  ignore_errors: yes


- name: add openjdk PPA
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "14"
    - openjdk_installed.rc != 0


- name: (jre-debian) | install openjdk
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - openjdk-8-jre
  when:
    - openjdk_installed.rc != 0

