---

- name: (install-redhat) | check logstash
  shell: rpm -qa | grep logstash
  register: check_logstash_redhat
  ignore_errors: yes


- name: (install-redhat) | stop logstash service
  service:
    name: logstash
    state: stopped
  ignore_errors: yes
  when: check_logstash_redhat.rc == 0


- name: (install-redhat) | pkill logstash process
  shell: pkill -9 -u logstash
  ignore_errors: yes
  when: check_logstash_redhat.rc == 0


- name: (install-redhat) | remove logstash
  yum:
    name: logstash
    state: absent
  when: check_logstash_redhat.rc == 0


- name: (install-redhat) | wget logstash package
  get_url:
    url: https://download.elastic.co/logstash/logstash/packages/centos/logstash-2.4.1.noarch.rpm
    dest: /tmp/logstash-2.4.1.noarch.rpm


- name: (install-redhat) | install logstash
  yum:
    name: /tmp/logstash-2.4.1.noarch.rpm
    state: present


- name: (install-redhat) | remove temp package
  file:
    path: /tmp/logstash-2.4.1.noarch.rpm
    state: absent

